CREATE TABLE images(
imageID INTEGER NOT NULL AUTO_INCREMENT,
productID INTEGER NOT NULL,
imagePath VARCHAR(255) NOT NULL,
PRIMARY KEY(imageID),
FOREIGN KEY(productID) REFERENCES products(productID) ON DELETE CASCADE
);
